// layout.js
import { SplashProvider } from "./context/splashcontext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Splashscreen from "./components/splashscreen";
import Bg from "./components/bg.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Youssef El Rhomari | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Splashscreen />
        <main className="relative border-2 border-black min-h-[calc(100vh-1rem)] sm:min-h-[calc(100vh-3rem)] m-4 sm:m-6 sm:mb-6 ">
          {/* Couche d'arrière-plan (z-0) */}
          <div className="absolute inset-0 z-0">
            <Bg />
          </div>

          {/* Couche de contenu (z-10), placée AU-DESSUS */}
          <div className="relative z-10">
            <SplashProvider>
            {children}
            </SplashProvider>
          </div>
        </main>
        <footer className="ml-10 text-[11px]">&copy; Youssef elrhomari</footer>
      </body>
    </html>
  );
}