import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Splashscreen from "./components/splashscreen";
import Bg from "./components/bg.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Youssef El Rhomari | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Splashscreen />
        <main className="border border-white min-h-[calc(100vh-1rem)] sm:min-h-[calc(100vh-3rem)] m-4 sm:m-6 sm:mb-6 ">
         <div className=""> {children} </div>
          <div className="absolute inset-0 z-[-1] "> <Bg/> </div>
        </main>
        <footer className="text-white ml-10 text-[11px]">&copy; Youssef elrhomari</footer>
      </body>
    </html>
  );
}
